export const stats = [
  { label: 'Mesas ocupadas', value: '14', detail: '+2 hoy' },
  { label: 'Ingresos', value: '$2.480', detail: '+12.4%' },
  { label: 'Pedidos activos', value: '23', detail: '8 en cocina' },
  { label: 'Clientes', value: '126', detail: '96 atendidos' },
]

export const tables = [
  {
    id: 1,
    number: 1,
    name: 'Mesa 1',
    status: 'Disponible',
    seats: 2,
    location: 'Terraza',
    token_qr: 'qr-token-mesa-01-a1b2c3d4',
    detail: 'Lista para asignar',
  },
  {
    id: 2,
    number: 2,
    name: 'Mesa 2',
    status: 'Ocupada',
    seats: 4,
    location: 'Terraza',
    token_qr: 'qr-token-mesa-02-e5f6g7h8',
    active: true,
    detail: '2 personas · Pedido #1042',
  },
  {
    id: 3,
    number: 3,
    name: 'Mesa 3',
    status: 'Reservada',
    seats: 4,
    location: 'Salón Principal',
    token_qr: 'qr-token-mesa-03-i9j0k1l2',
    detail: 'Reserva 13:30',
  },
  {
    id: 4,
    number: 4,
    name: 'Mesa 4',
    status: 'Ocupada',
    seats: 6,
    location: 'Salón Principal',
    token_qr: 'qr-token-mesa-04-m3n4o5p6',
    active: true,
    detail: '4 personas · Cuenta abierta',
  },
  {
    id: 5,
    number: 5,
    name: 'Mesa 5',
    status: 'Disponible',
    seats: 8,
    location: 'VIP',
    token_qr: 'qr-token-mesa-05-q7r8s9t0',
    detail: 'Pendiente limpieza',
  },
  {
    id: 6,
    number: 6,
    name: 'Mesa 6',
    status: 'Ocupada',
    seats: 4,
    location: 'Salón Principal',
    token_qr: 'qr-token-mesa-06-u1v2w3x4',
    active: true,
    detail: '3 personas · Pedido #1044',
  },
]

export const orders = [
  {
    id: '#1042',
    tableId: 2,
    client: 'Ana López',
    waiter: 'Carlos M.',
    table: 'Mesa 2',
    time: '12:35',
    elapsedMin: 14,
    total: '$84.50',
    state: 'En cocina',
    items: [
      { name: 'Lomo saltado', qty: 1, subtotal: '$24.00', notes: 'Término 3/4, con papas rústicas' },
      { name: 'Inca Kola 500ml', qty: 2, subtotal: '$16.00', notes: 'Bien fría con hielo' },
      { name: 'Tiramisú Artesanal', qty: 1, subtotal: '$12.00', notes: 'Servir al final' },
      { name: 'Papas Rústicas Trufadas', qty: 1, subtotal: '$14.00', notes: 'Salsa tártara aparte' },
    ],
  },
  {
    id: '#1043',
    tableId: 5,
    client: 'Javier Ruiz',
    waiter: 'Laura S.',
    table: 'Mesa 5',
    time: '12:42',
    elapsedMin: 18,
    total: '$58.00',
    state: 'Por servir',
    items: [
      { name: 'Ceviche mixto', qty: 1, subtotal: '$26.50', notes: 'Picante medio' },
      { name: 'Agua mineral con gas', qty: 1, subtotal: '$4.00', notes: 'Con rodaja de limón' },
      { name: 'Helado Artesanal', qty: 1, subtotal: '$9.50', notes: 'Sabor maracuyá y chocolate' },
    ],
  },
  {
    id: '#1044',
    tableId: 6,
    client: 'Familia Díaz',
    waiter: 'Jarrison P.',
    table: 'Mesa 6',
    time: '12:50',
    elapsedMin: 6,
    total: '$132.00',
    state: 'En cocina',
    items: [
      { name: 'Hamburguesa Smart Angus', qty: 2, subtotal: '$68.00', notes: 'Término medio, sin cebolla' },
      { name: 'Alitas BBQ x8', qty: 1, subtotal: '$28.00', notes: 'Salsa picante aparte' },
      { name: 'Limonada de Coco', qty: 3, subtotal: '$36.00', notes: 'Bien frapeadas' },
    ],
  },
  {
    id: '#1045',
    tableId: 4,
    client: 'Roberto V.',
    waiter: 'Laura S.',
    table: 'Mesa 4',
    time: '12:54',
    elapsedMin: 3,
    total: '$42.50',
    state: 'Pendiente',
    items: [
      { name: 'Nachos Supremos', qty: 1, subtotal: '$24.00', notes: 'Extra guacamole' },
      { name: 'Cerveza Corona', qty: 2, subtotal: '$18.50', notes: 'Con sal y limón' },
    ],
  },
  {
    id: '#1046',
    tableId: 1,
    client: 'Sofía Castro',
    waiter: 'Carlos M.',
    table: 'Mesa 1',
    time: '12:22',
    elapsedMin: 32,
    total: '$64.00',
    state: 'Entregado',
    items: [
      { name: 'Costillas BBQ St. Louis', qty: 1, subtotal: '$42.00', notes: 'Papas fritas' },
      { name: 'Cerveza Artesanal IPA', qty: 2, subtotal: '$22.00', notes: '' },
    ],
  },
]

export const categories = [
  { id: 1, name: 'Entradas', description: 'Para comenzar y compartir al centro de mesa' },
  { id: 2, name: 'Hamburguesas & Fuertes', description: 'Nuestras especialidades artesanales a la parrilla' },
  { id: 3, name: 'Bebidas & Cocteles', description: 'Refrescos naturales, cervezas y coctelería de autor' },
  { id: 4, name: 'Postres', description: 'El toque dulce perfecto para finalizar' },
]

export const dishes = [
  {
    id: 1,
    name: 'Nachos Supremos',
    id_categoria: 1,
    categoryName: 'Entradas',
    price: 24.0,
    priceFormatted: '$24.00',
    prepTime: 10,
    available: true,
    tag: 'Popular',
    description: 'Totopos crujientes con guacamole, queso cheddar fundido, pico de gallo y frijol refrito.',
    imageUrl: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 2,
    name: 'Alitas BBQ x8',
    id_categoria: 1,
    categoryName: 'Entradas',
    price: 28.0,
    priceFormatted: '$28.00',
    prepTime: 12,
    available: true,
    tag: 'Crujiente',
    description: 'Alitas de pollo crujientes bañadas en salsa BBQ artesanal con bastones de apio.',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 3,
    name: 'Hamburguesa Smart Angus',
    id_categoria: 2,
    categoryName: 'Hamburguesas & Fuertes',
    price: 34.0,
    priceFormatted: '$34.00',
    prepTime: 15,
    available: true,
    tag: 'Especial',
    description: '200g de carne Angus, queso cheddar madurado, tocineta ahumada, cebolla caramelizada y pan brioche.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 4,
    name: 'Costillas BBQ St. Louis',
    id_categoria: 2,
    categoryName: 'Hamburguesas & Fuertes',
    price: 42.0,
    priceFormatted: '$42.00',
    prepTime: 20,
    available: true,
    tag: 'Parrilla',
    description: 'Costillar de cerdo glaseado a fuego lento acompañado de papas rústicas y ensalada coleslaw.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 5,
    name: 'Limonada de Coco',
    id_categoria: 3,
    categoryName: 'Bebidas & Cocteles',
    price: 12.0,
    priceFormatted: '$12.00',
    prepTime: 5,
    available: true,
    tag: 'Refrescante',
    description: 'Limonada cremosa granizada preparada con leche de coco natural.',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 6,
    name: 'Tiramisú Artesanal',
    id_categoria: 4,
    categoryName: 'Postres',
    price: 14.0,
    priceFormatted: '$14.00',
    prepTime: 5,
    available: true,
    tag: 'Postre',
    description: 'Bizcocho bañado en café expreso con crema de queso mascarpone y cacao fino.',
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=500&q=80',
  },
]

export const menu = dishes.map((d) => ({
  name: d.name,
  price: d.priceFormatted,
  tag: d.tag,
}))
