export const stats = [
  { label: 'Mesas ocupadas', value: '14', detail: '+2 hoy' },
  { label: 'Ingresos', value: '$2.480', detail: '+12.4%' },
  { label: 'Pedidos activos', value: '23', detail: '8 en cocina' },
  { label: 'Clientes', value: '126', detail: '96 atendidos' },
]

export const tables = [
  {
    id: 1,
    number: 1,
    name: 'Mesa 1',
    status: 'Disponible',
    seats: 2,
    location: 'Terraza',
    token_qr: 'qr-token-mesa-01-a1b2c3d4',
    detail: 'Lista para asignar',
  },
  {
    id: 2,
    number: 2,
    name: 'Mesa 2',
    status: 'Ocupada',
    seats: 4,
    location: 'Terraza',
    token_qr: 'qr-token-mesa-02-e5f6g7h8',
    active: true,
    detail: '2 personas · Pedido #1042',
  },
  {
    id: 3,
    number: 3,
    name: 'Mesa 3',
    status: 'Reservada',
    seats: 4,
    location: 'Salón Principal',
    token_qr: 'qr-token-mesa-03-i9j0k1l2',
    detail: 'Reserva 13:30',
  },
  {
    id: 4,
    number: 4,
    name: 'Mesa 4',
    status: 'Ocupada',
    seats: 6,
    location: 'Salón Principal',
    token_qr: 'qr-token-mesa-04-m3n4o5p6',
    active: true,
    detail: '4 personas · Cuenta abierta',
  },
  {
    id: 5,
    number: 5,
    name: 'Mesa 5',
    status: 'Disponible',
    seats: 8,
    location: 'VIP',
    token_qr: 'qr-token-mesa-05-q7r8s9t0',
    detail: 'Pendiente limpieza',
  },
  {
    id: 6,
    number: 6,
    name: 'Mesa 6',
    status: 'Ocupada',
    seats: 4,
    location: 'Salón Principal',
    token_qr: 'qr-token-mesa-06-u1v2w3x4',
    active: true,
    detail: '3 personas · Pedido #1044',
  },
]

export const orders = [
  {
    id: '#1042',
    client: 'Ana López',
    table: 'Mesa 2',
    time: '12:35',
    total: '$84.50',
    state: 'En cocina',
    items: [
      { name: 'Lomo saltado', qty: 1, subtotal: '$24.00' },
      { name: 'Inca Kola', qty: 2, subtotal: '$16.00' },
      { name: 'Tiramisú', qty: 1, subtotal: '$12.00' },
    ],
  },
  {
    id: '#1043',
    client: 'Javier Ruiz',
    table: 'Mesa 5',
    time: '12:42',
    total: '$58.00',
    state: 'Por servir',
    items: [
      { name: 'Ceviche mixto', qty: 1, subtotal: '$26.50' },
      { name: 'Agua mineral', qty: 1, subtotal: '$4.00' },
      { name: 'Helado', qty: 1, subtotal: '$9.50' },
    ],
  },
  {
    id: '#1044',
    client: 'Familia Díaz',
    table: 'Mesa 6',
    time: '12:50',
    total: '$132.00',
    state: 'Preparando',
    items: [
      { name: 'Arroz con pollo', qty: 2, subtotal: '$52.00' },
      { name: 'Ensalada', qty: 1, subtotal: '$14.00' },
      { name: 'Jugo de maracuyá', qty: 2, subtotal: '$16.00' },
    ],
  },
]

export const menu = [
  { name: 'Lomo saltado', price: '$24.00', tag: 'Popular' },
  { name: 'Ceviche mixto', price: '$26.50', tag: 'Fresco' },
  { name: 'Jugo de maracuyá', price: '$8.00', tag: 'Bebida' },
  { name: 'Tiramisu', price: '$12.00', tag: 'Postre' },
]
